CREATE TABLE `job_history` (
  `build_tag` TEXT NOT NULL, 
  `job_name` TEXT NOT NULL, 
  `job_base_name` TEXT NOT NULL, 
  `job_url` TEXT NOT NULL, 
  `build_number` INTEGER NOT NULL, 
  `build_url` TEXT NOT NULL, 
  `build_start_time_in_millis` INTEGER NOT NULL, 
  `build_finish_time_in_millis` INTEGER NOT NULL, 
  `build_duration_time_in_millis` INTEGER NOT NULL, 
  `build_duration_time` TEXT NOT NULL, 
  `build_result` TEXT NOT NULL, 
  `build_params` TEXT, 
  `build_user_id` TEXT NOT NULL, 
  `build_user` TEXT, 
  `build_user_email` TEXT, 
  `node_name` TEXT NOT NULL, 
  `node_labels` TEXT NOT NULL, 
  `executor_number` INTEGER NOT NULL, 
  `workspace` TEXT NOT NULL, 
  `jenkins_home` TEXT NOT NULL, 
  `jenkins_url` TEXT NOT NULL, 
  `upstream_job_name` TEXT NOT NULL, 
  `upstream_build_number` INTEGER NOT NULL, 
  PRIMARY KEY(build_tag)
);
